### ISSUE TITLE
About the logo of this project

### ISSUE THREAD

**Issue by johnson86tw** [matryx/vuethereum#1]
Hello guys,

I just start building a vue 3 dapp library: https://github.com/chnejohnson/vue-dapp

I found this project's last commit is in three years ago. And I see this project's logo is very awesome to represent vue + ethereum, so I want to reach out to you about that, would it be possible for my project vue-dapp to use this logo?

@AustinGil @shessenauer 

![](https://raw.githubusercontent.com/matryx/vuethereum/master/static/logo-300x300.png)

**Comment by AustinGil** [comment]
Hi @chnejohnson, I wanted to give some time for the Matryx team to respond, but since they have not yet, I'll go ahead and get back to you. I am no longer a part of the organization so I really don't have a say, but I think they are still using this project and I'd assume they would want to avoid any confusion by letting another project use the same logo. I know we spent a bit of time and iterations on it. So I'm sorry to say, but I think it's best to come up with something else.

**Comment by johnson86tw** [comment]
Hi @AustinGil, it makes sense. I should create my own one. Very thanks for your reply!
